'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.5448
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AgriFact.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Agenda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Agenda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Aide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aide16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aide16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bloque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bloque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkAll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkAll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cheque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Clients() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clients", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Collapse_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collapse_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property complete16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("complete16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Compta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Compta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CopyHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CopyHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Corbeille() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Corbeille", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cube() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cube", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;!-- Définitions données pour la version 1.5 --&gt;
        '''&lt;DefinitionDonnees&gt;
        '''	&lt;Tables&gt;
        '''		&lt;Table nom=&quot;Entreprise&quot; cle=&quot;nEntreprise&quot; autonum=&quot;nEntreprise&quot; /&gt;
        '''		&lt;Table nom=&quot;TelephoneEntreprise&quot; cle=&quot;nEntreprise,Type&quot; /&gt;
        '''		&lt;Table nom=&quot;Personne&quot; cle=&quot;nPersonne&quot; autonum=&quot;nPersonne&quot; /&gt;
        '''		&lt;Table nom=&quot;Telephone&quot; cle=&quot;nPersonne,Type&quot; /&gt;
        '''		&lt;Table nom=&quot;Evenement&quot; cle=&quot;nEvenement&quot; autonum=&quot;nEvenement&quot; /&gt;
        '''		&lt;Table nom=&quot;Produit&quot; cle=&quot;nProduit&quot; autonum=&quot;nProduit&quot; /&gt;
        '''		&lt;Table nom=&quot;C [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property DefinitionDonnees() As String
            Get
                Return ResourceManager.GetString("DefinitionDonnees", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property DialHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DialHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EditTableHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditTableHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EntityDataModel_OtherModelService() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EntityDataModel_OtherModelService", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eps_openHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eps_openHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Expand_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Expand_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exportcsv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportcsv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Factures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Factures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Finance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Finance16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finance16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fleche() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fleche", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FranceR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FranceR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GetPermission() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GetPermission", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icone_admin16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icone_admin16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icone_update_appli16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icone_update_appli16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icone_util16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icone_util16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property impr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property impr32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impr32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property liste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property liste_reglement() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liste_reglement", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo_Agrifact() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo_Agrifact", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;ArrayOfMenu&gt;
        '''  &lt;Menu Nom=&quot;Partenaires&quot; Text=&quot;Partenaires&quot; Image=&quot;Clients&quot;&gt;
        '''    &lt;Items&gt;
        '''      &lt;Item Type=&quot;MenuItem&quot; Nom=&quot;Clients&quot; Text=&quot;Clients&quot; Form=&quot;&quot;  Image=&quot;Fleche&quot; IconSize=&quot;16&quot;/&gt;
        '''      &lt;Item Type=&quot;MenuItem&quot; Nom=&quot;Fournisseurs&quot; Text=&quot;Fournisseurs&quot; Form=&quot;&quot;  Image=&quot;Fleche&quot; IconSize=&quot;16&quot;/&gt;
        '''      &lt;Item Type=&quot;MenuItem&quot; Nom=&quot;Contacts&quot; Text=&quot;Contacts&quot; Form=&quot;FrListePersonne&quot;  Image=&quot;Fleche&quot; IconSize=&quot;16&quot;/&gt;
        '''      &lt;Item Type=&quot;MenuItem&quot; Nom=&quot;ListeParam&quot; Text=&quot;Listes P [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Menus() As String
            Get
                Return ResourceManager.GetString("Menus", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property netviewer16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netviewer16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewCardHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewCardHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewFactures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewFactures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openfolderHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openfolderHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property outils() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outils", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prev24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prev24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preview32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preview32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrimaryKeyHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrimaryKeyHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reglement_rejete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reglement_rejete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Removehyperlink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Removehyperlink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Retry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Retry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RoutingSlipHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RoutingSlipHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Site() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Site", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suppr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suppr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Suppr24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Suppr24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SychronizeListHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SychronizeListHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ultravnc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ultravnc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uncheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uncheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property userAccounts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("userAccounts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
