'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4952
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ControleTracabilite.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property actif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BarCodeHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarCodeHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BuilderDialog_movedown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuilderDialog_movedown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BuilderDialog_moveup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuilderDialog_moveup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property compo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property controles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("controles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CopyHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CopyHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icone() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icone", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property impr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inactif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inactif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property liste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ArrayOfMenu&gt;
        '''  &lt;Menu Nom=&quot;Donnees&quot; Text=&quot;Données&quot; Image=&quot;&quot;&gt;
        '''    &lt;Items&gt;
        '''      &lt;Item Type=&quot;Separator&quot; Nom=&quot;Sep&quot; Text=&quot;Fournisseurs&quot; /&gt;
        '''      &lt;Item Type=&quot;MenuItem&quot; Nom=&quot;ListeFour&quot; Text=&quot;Liste des fournisseurs&quot; Form=&quot;Fournisseurs.FrListeFourn&quot; Image=&quot;liste&quot; IconSize=&quot;16&quot; /&gt;
        '''      &lt;Item Type=&quot;MenuItem&quot; Nom=&quot;SaisieFour&quot; Text=&quot;Nouveau fournisseur&quot; Form=&quot;Fournisseurs.FrSaisieFourn&quot; Image=&quot;_new&quot; IconSize=&quot;16&quot; /&gt;
        '''      &lt;Item Type=&quot;Separator&quot; Nom=&quot;Sep&quot; Text=&quot;Produits&quot; /&gt; [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Menus() As String
            Get
                Return ResourceManager.GetString("Menus", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property netviewer16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netviewer16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewCardHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewCardHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property outils() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outils", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RefreshDocViewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RepeatHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RepeatHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Resultats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resultats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Retry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Retry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SaveFormDesignHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveFormDesignHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property security() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("security", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suppr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suppr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ultravnc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ultravnc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        '''&lt;ArrayOfDefinitionControle&gt;
        '''  &lt;DefinitionControle&gt;
        '''    &lt;IdControle&gt;1&lt;/IdControle&gt;
        '''    &lt;GroupeControle&gt;CONTRÔLE FERMETURE CONDITIONNEMENT&lt;/GroupeControle&gt;
        '''    &lt;Libelle&gt;Contrôle visuel :&lt;/Libelle&gt;
        '''    &lt;Type&gt;RadioButton&lt;/Type&gt;
        '''    &lt;ValeursPossibles&gt;Bon;Mauvais&lt;/ValeursPossibles&gt;
        '''    &lt;Baremes&gt;
        '''      &lt;Bareme&gt;
        '''        &lt;Expression&gt;val=&apos;Bon&apos;&lt;/Expression&gt;
        '''        &lt;ResultatConformite&gt;false&lt;/ResultatConformite&gt;
        '''        &lt;ActionCorrective&gt;Faire une correction.&lt;/ActionC [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property XmlControles() As String
            Get
                Return ResourceManager.GetString("XmlControles", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
