'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.5448
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AgrigestEDI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AddTableHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddTableHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Book_StackOfReportsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Book_StackOfReportsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CheckSpellingHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheckSpellingHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cloture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A.
        '''</summary>
        Friend ReadOnly Property CODE_TYPEINV_ANIMAUX() As String
            Get
                Return ResourceManager.GetString("CODE_TYPEINV_ANIMAUX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à V.
        '''</summary>
        Friend ReadOnly Property CODE_TYPEINV_AVAUXCULTURES() As String
            Get
                Return ResourceManager.GetString("CODE_TYPEINV_AVAUXCULTURES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à F.
        '''</summary>
        Friend ReadOnly Property CODE_TYPEINV_FACONSCULTURALES() As String
            Get
                Return ResourceManager.GetString("CODE_TYPEINV_FACONSCULTURALES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à M.
        '''</summary>
        Friend ReadOnly Property CODE_TYPEINV_STOCKSENMAG() As String
            Get
                Return ResourceManager.GetString("CODE_TYPEINV_STOCKSENMAG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à P.
        '''</summary>
        Friend ReadOnly Property CODE_TYPEINV_STOCKSPRODFINIS() As String
            Get
                Return ResourceManager.GetString("CODE_TYPEINV_STOCKSPRODFINIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à T.
        '''</summary>
        Friend ReadOnly Property CODE_TYPEINV_STOCKSPRODTERRE() As String
            Get
                Return ResourceManager.GetString("CODE_TYPEINV_STOCKSPRODTERRE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à O.
        '''</summary>
        Friend ReadOnly Property CODE_TYPEMAT_OUTIL() As String
            Get
                Return ResourceManager.GetString("CODE_TYPEMAT_OUTIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à T.
        '''</summary>
        Friend ReadOnly Property CODE_TYPEMAT_TRACTEUR() As String
            Get
                Return ResourceManager.GetString("CODE_TYPEMAT_TRACTEUR", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Collapsed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collapsed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property compta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property create() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("create", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DeleteHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DownArrowShort_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownArrowShort_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ArrayOfMenu&gt;
        '''   &lt;Menu Nom=&quot;Journaux&quot; Text=&quot;Journaux&quot; Image=&quot;create&quot;&gt;
        '''    &lt;Items&gt;
        '''		&lt;Item Type=&quot;Separator&quot; Master=&quot;Journaux&quot; Nom=&quot;Sep&quot; Text=&quot;Journaux&quot; /&gt;
        '''		&lt;Item Type=&quot;MenuItem&quot; Master=&quot;Journaux&quot; Nom=&quot;JournalAchats&quot; Text=&quot;Journaux&quot; Etat=&quot;&quot; Image=&quot;create&quot; IconSize=&quot;16&quot; LockEmptyDossier=&quot;true&quot;/&gt;
        '''		&lt;!--&lt;Item Type=&quot;MenuItem&quot; Master=&quot;Journaux&quot; Nom=&quot;JournalVentes&quot; Text=&quot;Journal ventes&quot; Etat=&quot;&quot; Image=&quot;create&quot; IconSize=&quot;16&quot; LockEmptyDossier=&quot;true&quot;/&gt;
        '''		&lt;Item Type=&quot;MenuIt [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Etats() As String
            Get
                Return ResourceManager.GetString("Etats", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Expanded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Expanded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exportcsv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportcsv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property first() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("first", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flag_redHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flag_redHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ArrayOfFormatFichierIsagri xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;FormatFichierIsagri Version=&quot;0200000&quot;&gt;
        '''    &lt;FormatsLigne&gt;
        '''      &lt;item&gt;
        '''        &lt;key&gt;
        '''          &lt;string&gt;VER&lt;/string&gt;
        '''        &lt;/key&gt;
        '''        &lt;value&gt;
        '''          &lt;string&gt;VER   .{1,27}(?&amp;lt;Destruction&amp;gt;\d{1})&lt;/string&gt;
        '''        &lt;/value&gt;
        '''      &lt;/item&gt;
        '''      &lt;item&gt;
        '''        &lt;key&gt;
        '''          &lt;string&gt;DOS&lt;/string&gt;
        '''        &lt;/key&gt;
        '''        [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property FormatFichierIsagri() As String
            Get
                Return ResourceManager.GetString("FormatFichierIsagri", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property GetPermission() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GetPermission", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icone_util16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icone_util16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icone_Ventes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icone_Ventes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property impr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property liste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;NewDataSet&gt;
        '''  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''      &lt;xs:complexType&gt;
        '''        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''          &lt;xs:element name=&quot;Table1&quot;&gt;
        '''            &lt;xs:complexType&gt;
        '''              &lt;xs:sequence&gt;
        '''                &lt;xs:element name=&quot;Champ&quot; type=&quot;xs:str [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property ListeChampBalance() As String
            Get
                Return ResourceManager.GetString("ListeChampBalance", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Méthode détaillée par mat.
        '''</summary>
        Friend ReadOnly Property M1() As String
            Get
                Return ResourceManager.GetString("M1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Barème forfaitaire ha.
        '''</summary>
        Friend ReadOnly Property M2() As String
            Get
                Return ResourceManager.GetString("M2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ArrayOfMenu&gt;
        '''  &lt;Menu Nom=&quot;General&quot; Text=&quot;Général&quot; Image=&quot;compta&quot;&gt;
        '''    &lt;Items&gt;
        '''      &lt;Item Type=&quot;Separator&quot; Master=&quot;SepEcr&quot; Nom=&quot;SepEcr&quot; Text=&quot;Ecritures&quot; Acceuil=&quot;true&quot;/&gt;
        '''      &lt;Item Type=&quot;MenuItem&quot; Master=&quot;SepEcr&quot; Nom=&quot;SaisiePiece&quot; Text=&quot;Saisie sur pièce&quot; Form=&quot;FrSaisiePiece&quot; Image=&quot;_new&quot; IconSize=&quot;16&quot; Dialog=&quot;true&quot; LockEmptyDossier=&quot;true&quot; Acceuil=&quot;true&quot;&gt;
        '''        &lt;Description&gt;Saisir les écritures une à une&lt;/Description&gt;
        '''      &lt;/Item&gt;
        '''      &lt;Item Type=&quot;MenuItem [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Menus() As String
            Get
                Return ResourceManager.GetString("Menus", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property modif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property netviewer16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netviewer16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewDocumentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDocumentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewReportHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewReportHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property outils() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outils", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RefreshDocViewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property security() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("security", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sort() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sort", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suppr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suppr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TableHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TableHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property task() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("task", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ultravnc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ultravnc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UpArrowShort_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UpArrowShort_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property utils() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("utils", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
