'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.5446
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AgrigestEDI.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ACTIVITE GENERALE.
        '''</summary>
        Friend Shared ReadOnly Property ACTIVITEGENERALE() As String
            Get
                Return ResourceManager.GetString("ACTIVITEGENERALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le nom de classe est incorrect.
        '''</summary>
        Friend Shared ReadOnly Property AfficherEcran_LeNomDeClasseEstIncorrect() As String
            Get
                Return ResourceManager.GetString("AfficherEcran_LeNomDeClasseEstIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La classe définie n&apos;est pas un écran.
        '''</summary>
        Friend Shared ReadOnly Property AfficherEcran_PasUnEcran() As String
            Get
                Return ResourceManager.GetString("AfficherEcran_PasUnEcran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Arrêter la téléintervention.
        '''</summary>
        Friend Shared ReadOnly Property ArreterLaTeleintervention() As String
            Get
                Return ResourceManager.GetString("ArreterLaTeleintervention", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Chargement des données....
        '''</summary>
        Friend Shared ReadOnly Property ChargementDesDonnees() As String
            Get
                Return ResourceManager.GetString("ChargementDesDonnees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Code Utilisateur invalide.
        '''</summary>
        Friend Shared ReadOnly Property Cle_CodeUtilisateurInvalide() As String
            Get
                Return ResourceManager.GetString("Cle_CodeUtilisateurInvalide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La clé d&apos;activation a expiré depuis le {0:dd/MM/yy}..
        '''</summary>
        Friend Shared ReadOnly Property Cle_Expiree() As String
            Get
                Return ResourceManager.GetString("Cle_Expiree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La clé d&apos;activation n&apos;est pas valide..
        '''</summary>
        Friend Shared ReadOnly Property Cle_PasValide() As String
            Get
                Return ResourceManager.GetString("Cle_PasValide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Clôture.
        '''</summary>
        Friend Shared ReadOnly Property Cloture() As String
            Get
                Return ResourceManager.GetString("Cloture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez pas clôturer cet exercice car la balance n&apos;est pas juste. Votre écart est de {0}€.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_AvertissementProblemeBalance() As String
            Get
                Return ResourceManager.GetString("Cloture_AvertissementProblemeBalance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Calcul des reports.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_CalculDesReports() As String
            Get
                Return ResourceManager.GetString("Cloture_CalculDesReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Clôture provisoire réalisée.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_ClotureProvisoireOK() As String
            Get
                Return ResourceManager.GetString("Cloture_ClotureProvisoireOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Génération du nouveau nom de l&apos;exercice.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_CreerCodeExercice() As String
            Get
                Return ResourceManager.GetString("Cloture_CreerCodeExercice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Création du nouvel exercice.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_CreerNouvelExercice() As String
            Get
                Return ResourceManager.GetString("Cloture_CreerNouvelExercice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Détermination des dates de l&apos;exercice actuel.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_DateAncienDossier() As String
            Get
                Return ResourceManager.GetString("Cloture_DateAncienDossier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Détermination des dates du nouvel exercice.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_DateNouveauDossier() As String
            Get
                Return ResourceManager.GetString("Cloture_DateNouveauDossier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mise à jour des données de report.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_EnregistrerReport() As String
            Get
                Return ResourceManager.GetString("Cloture_EnregistrerReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exercice clôturé.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_ExerciceCloture() As String
            Get
                Return ResourceManager.GetString("Cloture_ExerciceCloture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;exercice n&apos;a plus de clôture.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_NoCloture() As String
            Get
                Return ResourceManager.GetString("Cloture_NoCloture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez changer d&apos;année pour votre début d&apos;exercice.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_PlusDeCodeDispo() As String
            Get
                Return ResourceManager.GetString("Cloture_PlusDeCodeDispo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Détermination d&apos;un exercice existant.
        '''</summary>
        Friend Shared ReadOnly Property Cloture_TrouverExercice() As String
            Get
                Return ResourceManager.GetString("Cloture_TrouverExercice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Comptabilité clôturée.
        '''</summary>
        Friend Shared ReadOnly Property ComptabiliteCloturee() As String
            Get
                Return ResourceManager.GetString("ComptabiliteCloturee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez mettre de date ayant un écart supérieur à 14 mois.
        '''</summary>
        Friend Shared ReadOnly Property Date_Ecart14Mois() As String
            Get
                Return ResourceManager.GetString("Date_Ecart14Mois", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;exercice doit au minimum durer un jour..
        '''</summary>
        Friend Shared ReadOnly Property Date_Ecart1Jour() As String
            Get
                Return ResourceManager.GetString("Date_Ecart1Jour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choix de l&apos;exploitation.
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_ChoixDeLExploitation() As String
            Get
                Return ResourceManager.GetString("Demarrage_ChoixDeLExploitation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choix de l&apos;exercice.
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_ChoixDuDossier() As String
            Get
                Return ResourceManager.GetString("Demarrage_ChoixDuDossier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Compactage de la base.
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_CompactageDeLaBase() As String
            Get
                Return ResourceManager.GetString("Demarrage_CompactageDeLaBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Connexion à la base.
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_ConnexionBase() As String
            Get
                Return ResourceManager.GetString("Demarrage_ConnexionBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cette copie d&apos;Agrigest n&apos;est pas activée.
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_CopiePasActivee() As String
            Get
                Return ResourceManager.GetString("Demarrage_CopiePasActivee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ouverture de l&apos;application.
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_OuvertureDeLApplication() As String
            Get
                Return ResourceManager.GetString("Demarrage_OuvertureDeLApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Restauration.
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_Restauration() As String
            Get
                Return ResourceManager.GetString("Demarrage_Restauration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;application va revenir à la dernière sauvegarde automatique..
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_Restore() As String
            Get
                Return ResourceManager.GetString("Demarrage_Restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La base de données est introuvable..
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_Restore1() As String
            Get
                Return ResourceManager.GetString("Demarrage_Restore1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vérification de la clé d&apos;activation.
        '''</summary>
        Friend Shared ReadOnly Property Demarrage_VerifCle() As String
            Get
                Return ResourceManager.GetString("Demarrage_VerifCle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous supprimer l&apos;exercice : {0} ?.
        '''</summary>
        Friend Shared ReadOnly Property Dossier_AskSuppression() As String
            Get
                Return ResourceManager.GetString("Dossier_AskSuppression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention : il existe des pièces avant cette date pour un exercice..
        '''</summary>
        Friend Shared ReadOnly Property Dossier_AvertissementTransfert() As String
            Get
                Return ResourceManager.GetString("Dossier_AvertissementTransfert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Celles-ci seront transférées lors de la modification..
        '''</summary>
        Friend Shared ReadOnly Property Dossier_AvertissementTransfert2() As String
            Get
                Return ResourceManager.GetString("Dossier_AvertissementTransfert2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention il existe des pièces après cette date pour un exercice..
        '''</summary>
        Friend Shared ReadOnly Property Dossier_AvertissementTransfert3() As String
            Get
                Return ResourceManager.GetString("Dossier_AvertissementTransfert3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ce code exploitation est déjà utilisé..
        '''</summary>
        Friend Shared ReadOnly Property Dossier_CodeExplUtilise() As String
            Get
                Return ResourceManager.GetString("Dossier_CodeExplUtilise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Il existe déjà un exercice comprenant cette date. Veuillez changer de date..
        '''</summary>
        Friend Shared ReadOnly Property Dossier_PbChoixDate() As String
            Get
                Return ResourceManager.GetString("Dossier_PbChoixDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Création d&apos;exercice.
        '''</summary>
        Friend Shared ReadOnly Property Dossier_TextCreation() As String
            Get
                Return ResourceManager.GetString("Dossier_TextCreation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Modification d&apos;exercice.
        '''</summary>
        Friend Shared ReadOnly Property Dossier_TextModif() As String
            Get
                Return ResourceManager.GetString("Dossier_TextModif", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ecriture du fichier....
        '''</summary>
        Friend Shared ReadOnly Property EcritureDuFichier() As String
            Get
                Return ResourceManager.GetString("EcritureDuFichier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enregistrement.
        '''</summary>
        Friend Shared ReadOnly Property Enregistrement() As String
            Get
                Return ResourceManager.GetString("Enregistrement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enregistrement des données....
        '''</summary>
        Friend Shared ReadOnly Property EnregistrementDesDonnees() As String
            Get
                Return ResourceManager.GetString("EnregistrementDesDonnees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous enregistrer les modifications ?.
        '''</summary>
        Friend Shared ReadOnly Property EnregistrerLesModifications() As String
            Get
                Return ResourceManager.GetString("EnregistrerLesModifications", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Souhaitez-vous enregistrer ce rapport ?.
        '''</summary>
        Friend Shared ReadOnly Property EnregistrerRapport() As String
            Get
                Return ResourceManager.GetString("EnregistrerRapport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Une erreur s&apos;est produite : .
        '''</summary>
        Friend Shared ReadOnly Property ErreurAppli() As String
            Get
                Return ResourceManager.GetString("ErreurAppli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Une erreur s&apos;est produite, l&apos;application va se terminer : .
        '''</summary>
        Friend Shared ReadOnly Property ErreurCritique() As String
            Get
                Return ResourceManager.GetString("ErreurCritique", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Erreur d&apos;enregistrement.
        '''</summary>
        Friend Shared ReadOnly Property ErreurDEnregistrement() As String
            Get
                Return ResourceManager.GetString("ErreurDEnregistrement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Erreur de saisie.
        '''</summary>
        Friend Shared ReadOnly Property ErreurDeSaisie() As String
            Get
                Return ResourceManager.GetString("ErreurDeSaisie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Erreur Suppression.
        '''</summary>
        Friend Shared ReadOnly Property ErreurSuppression() As String
            Get
                Return ResourceManager.GetString("ErreurSuppression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Activité début.
        '''</summary>
        Friend Shared ReadOnly Property Etats_ActDeb() As String
            Get
                Return ResourceManager.GetString("Etats_ActDeb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Activité fin.
        '''</summary>
        Friend Shared ReadOnly Property Etats_ActFin() As String
            Get
                Return ResourceManager.GetString("Etats_ActFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imprimer.
        '''</summary>
        Friend Shared ReadOnly Property Etats_BtImprimer() As String
            Get
                Return ResourceManager.GetString("Etats_BtImprimer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Compte début.
        '''</summary>
        Friend Shared ReadOnly Property Etats_CptDeb() As String
            Get
                Return ResourceManager.GetString("Etats_CptDeb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Compte fin.
        '''</summary>
        Friend Shared ReadOnly Property Etats_CptFin() As String
            Get
                Return ResourceManager.GetString("Etats_CptFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Date de début de période.
        '''</summary>
        Friend Shared ReadOnly Property Etats_DateDeb() As String
            Get
                Return ResourceManager.GetString("Etats_DateDeb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Date de fin de période.
        '''</summary>
        Friend Shared ReadOnly Property Etats_DateFin() As String
            Get
                Return ResourceManager.GetString("Etats_DateFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edité avec AgrigestEDI le {0:dd/MM/yy}.
        '''</summary>
        Friend Shared ReadOnly Property Etats_EditeAvecAgrigestEDI() As String
            Get
                Return ResourceManager.GetString("Etats_EditeAvecAgrigestEDI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Période du {0} au {1}.
        '''</summary>
        Friend Shared ReadOnly Property Etats_LibPeriode() As String
            Get
                Return ResourceManager.GetString("Etats_LibPeriode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le relevé de compte contient  des opérations qui ne sont pas libellées en euros..
        '''</summary>
        Friend Shared ReadOnly Property Etebac_VerifMonnaie() As String
            Get
                Return ResourceManager.GetString("Etebac_VerifMonnaie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exercice du {0:dd/MM/yyyy} au {1:dd/MM/yyyy}.
        '''</summary>
        Friend Shared ReadOnly Property ExerciceDuDate0AuDate1() As String
            Get
                Return ResourceManager.GetString("ExerciceDuDate0AuDate1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous supprimer tous les exercices de cette exploitation  : {0} ?.
        '''</summary>
        Friend Shared ReadOnly Property Expl_AskSuppression() As String
            Get
                Return ResourceManager.GetString("Expl_AskSuppression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélectionnez la base de données à intégrer.
        '''</summary>
        Friend Shared ReadOnly Property Expl_BDDAIntegrer() As String
            Get
                Return ResourceManager.GetString("Expl_BDDAIntegrer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Indiquez le chemin de la base de données..
        '''</summary>
        Friend Shared ReadOnly Property Expl_BrowseBDD() As String
            Get
                Return ResourceManager.GetString("Expl_BrowseBDD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Indiquez le chemin de la base de données du plan type..
        '''</summary>
        Friend Shared ReadOnly Property Expl_BrowseBDDPlanType() As String
            Get
                Return ResourceManager.GetString("Expl_BrowseBDDPlanType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;exercice {0} est introuvable..
        '''</summary>
        Friend Shared ReadOnly Property Expl_DossierIntrouvable() As String
            Get
                Return ResourceManager.GetString("Expl_DossierIntrouvable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir enlever l&apos;exploitation &apos;{0}&apos; de la liste ?.
        '''</summary>
        Friend Shared ReadOnly Property Expl_EnleverExploitation() As String
            Get
                Return ResourceManager.GetString("Expl_EnleverExploitation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;exploitation {0} est introuvable..
        '''</summary>
        Friend Shared ReadOnly Property Expl_ExplIntrouvable() As String
            Get
                Return ResourceManager.GetString("Expl_ExplIntrouvable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exploitation supprimée.
        '''</summary>
        Friend Shared ReadOnly Property Expl_ExploitationSupprimee() As String
            Get
                Return ResourceManager.GetString("Expl_ExploitationSupprimee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous aussi supprimer la base de données &apos;{0}&apos; ?.
        '''</summary>
        Friend Shared ReadOnly Property Expl_SupprimerBDD() As String
            Get
                Return ResourceManager.GetString("Expl_SupprimerBDD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir un nom d&apos;exploitation.
        '''</summary>
        Friend Shared ReadOnly Property Expl_VerfiSaisieNom() As String
            Get
                Return ResourceManager.GetString("Expl_VerfiSaisieNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir un code d&apos;exploitation ex : 00001.
        '''</summary>
        Friend Shared ReadOnly Property Expl_VerifSaisieCode() As String
            Get
                Return ResourceManager.GetString("Expl_VerifSaisieCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir annuler les exports sélectionnés ?.
        '''</summary>
        Friend Shared ReadOnly Property Export_AskAnnulation() As String
            Get
                Return ResourceManager.GetString("Export_AskAnnulation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucune écriture n&apos;a pu être exportée..
        '''</summary>
        Friend Shared ReadOnly Property Export_AucuneEcrExportee() As String
            Get
                Return ResourceManager.GetString("Export_AucuneEcrExportee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Répertoire contenant les exports de comptabilité AgrigestEDI pour transmission au comptable..
        '''</summary>
        Friend Shared ReadOnly Property Export_DescriptionRaccourciExports() As String
            Get
                Return ResourceManager.GetString("Export_DescriptionRaccourciExports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export des activités....
        '''</summary>
        Friend Shared ReadOnly Property Export_ExportActi() As String
            Get
                Return ResourceManager.GetString("Export_ExportActi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export des pièces....
        '''</summary>
        Friend Shared ReadOnly Property Export_ExportPieces() As String
            Get
                Return ResourceManager.GetString("Export_ExportPieces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export du plan comptable....
        '''</summary>
        Friend Shared ReadOnly Property Export_ExportPLC() As String
            Get
                Return ResourceManager.GetString("Export_ExportPLC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export des codes TVA....
        '''</summary>
        Friend Shared ReadOnly Property Export_ExportTVA() As String
            Get
                Return ResourceManager.GetString("Export_ExportTVA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;exportation n&apos;a pas pu être réalisée à cause des problèmes suivants :.
        '''</summary>
        Friend Shared ReadOnly Property Export_RecapProblemes() As String
            Get
                Return ResourceManager.GetString("Export_RecapProblemes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exportation réalisée avec succès.
        '''</summary>
        Friend Shared ReadOnly Property Export_Succes() As String
            Get
                Return ResourceManager.GetString("Export_Succes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le fichier {0} existe déjà, voulez-vous le remplacer ?.
        '''</summary>
        Friend Shared ReadOnly Property FIchierExistant() As String
            Get
                Return ResourceManager.GetString("FIchierExistant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fichier inexistant..
        '''</summary>
        Friend Shared ReadOnly Property FichierInexistant() As String
            Get
                Return ResourceManager.GetString("FichierInexistant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le fichier {0} n&apos;existe pas.
        '''</summary>
        Friend Shared ReadOnly Property FichierIntrouvable() As String
            Get
                Return ResourceManager.GetString("FichierIntrouvable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention : Etes-vous sur de vouloir remplacer cet exercice ?.
        '''</summary>
        Friend Shared ReadOnly Property Import_ConfirmationEcraseDossier() As String
            Get
                Return ResourceManager.GetString("Import_ConfirmationEcraseDossier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Erreur d&apos;importation.
        '''</summary>
        Friend Shared ReadOnly Property Import_ErreurDImportation() As String
            Get
                Return ResourceManager.GetString("Import_ErreurDImportation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La pièce {0} du {1:dd/MM/yyyy} n&apos;est pas équilibrée..
        '''</summary>
        Friend Shared ReadOnly Property Import_ErreurEquilibre() As String
            Get
                Return ResourceManager.GetString("Import_ErreurEquilibre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Il y a un problème dans l&apos;enregistrement de pièce..
        '''</summary>
        Friend Shared ReadOnly Property Import_ErreurFichier() As String
            Get
                Return ResourceManager.GetString("Import_ErreurFichier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ligne DOS avant la ligne VER. Veuillez vérifier votre fichier..
        '''</summary>
        Friend Shared ReadOnly Property Import_ErreurLignes1() As String
            Get
                Return ResourceManager.GetString("Import_ErreurLignes1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ligne EXO avant la ligne DOS. Veuillez vérifier votre fichier..
        '''</summary>
        Friend Shared ReadOnly Property Import_ErreurLignes2() As String
            Get
                Return ResourceManager.GetString("Import_ErreurLignes2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ligne ECR avant la ligne EXO. Veuillez vérifier votre fichier..
        '''</summary>
        Friend Shared ReadOnly Property Import_ErreurLignes3() As String
            Get
                Return ResourceManager.GetString("Import_ErreurLignes3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Il n&apos;y a pas de données dans ce fichier. Veuillez en prendre un autre..
        '''</summary>
        Friend Shared ReadOnly Property Import_FichierVide() As String
            Get
                Return ResourceManager.GetString("Import_FichierVide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le fichier {0} n&apos;est pas formaté dans une version connu de AgriGestEDI.
        '''</summary>
        Friend Shared ReadOnly Property Import_FormatECRInconnu() As String
            Get
                Return ResourceManager.GetString("Import_FormatECRInconnu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;importation n&apos;a pas pu être réalisée à cause des problèmes suivants :.
        '''</summary>
        Friend Shared ReadOnly Property Import_RecapProblemes() As String
            Get
                Return ResourceManager.GetString("Import_RecapProblemes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;importation a été effectuée avec succès.
        '''</summary>
        Friend Shared ReadOnly Property Import_Succes() As String
            Get
                Return ResourceManager.GetString("Import_Succes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible de supprimer la pièce : .
        '''</summary>
        Friend Shared ReadOnly Property ImpossibleDeSupprimerPiece() As String
            Get
                Return ResourceManager.GetString("ImpossibleDeSupprimerPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Information.
        '''</summary>
        Friend Shared ReadOnly Property Information() As String
            Get
                Return ResourceManager.GetString("Information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Initialisation.
        '''</summary>
        Friend Shared ReadOnly Property Initialisation() As String
            Get
                Return ResourceManager.GetString("Initialisation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lancer la téléintervention.
        '''</summary>
        Friend Shared ReadOnly Property LancerLaTeleintervention() As String
            Get
                Return ResourceManager.GetString("LancerLaTeleintervention", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Un modèle portant ce nom existe déjà..
        '''</summary>
        Friend Shared ReadOnly Property Modele_Collision() As String
            Get
                Return ResourceManager.GetString("Modele_Collision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Création de modèle.
        '''</summary>
        Friend Shared ReadOnly Property Modele_CreationDeModele() As String
            Get
                Return ResourceManager.GetString("Modele_CreationDeModele", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enregistrement de modèle.
        '''</summary>
        Friend Shared ReadOnly Property Modele_Enregistrement() As String
            Get
                Return ResourceManager.GetString("Modele_Enregistrement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ce modèle n&apos;existe pas.
        '''</summary>
        Friend Shared ReadOnly Property Modele_ModeleIntrouvable() As String
            Get
                Return ResourceManager.GetString("Modele_ModeleIntrouvable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le modèle est supprimé.
        '''</summary>
        Friend Shared ReadOnly Property Modele_ModeleSupprime() As String
            Get
                Return ResourceManager.GetString("Modele_ModeleSupprime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous n&apos;avez aucun modèle de sélectionné.
        '''</summary>
        Friend Shared ReadOnly Property Modele_ProblemeSelection() As String
            Get
                Return ResourceManager.GetString("Modele_ProblemeSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Suppression de modéle.
        '''</summary>
        Friend Shared ReadOnly Property Modele_Suppression() As String
            Get
                Return ResourceManager.GetString("Modele_Suppression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir le nom du modèle..
        '''</summary>
        Friend Shared ReadOnly Property Modele_VeuillezSaisirLeNomDuModele() As String
            Get
                Return ResourceManager.GetString("Modele_VeuillezSaisirLeNomDuModele", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ouverture de l&apos;état....
        '''</summary>
        Friend Shared ReadOnly Property OuvertureEtat() As String
            Get
                Return ResourceManager.GetString("OuvertureEtat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pièce supprimée.
        '''</summary>
        Friend Shared ReadOnly Property PieceSupprimee() As String
            Get
                Return ResourceManager.GetString("PieceSupprimee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;activité {0} ne peut être associée au compte {1}.
        '''</summary>
        Friend Shared ReadOnly Property PLC_ActiInterdite() As String
            Get
                Return ResourceManager.GetString("PLC_ActiInterdite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affectation d&apos;activités.
        '''</summary>
        Friend Shared ReadOnly Property PLC_AffectionActi() As String
            Get
                Return ResourceManager.GetString("PLC_AffectionActi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter les activités sélectionnées.
        '''</summary>
        Friend Shared ReadOnly Property PLC_AjouterActi() As String
            Get
                Return ResourceManager.GetString("PLC_AjouterActi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choix du compte....
        '''</summary>
        Friend Shared ReadOnly Property PLC_ChoixDuCompte() As String
            Get
                Return ResourceManager.GetString("PLC_ChoixDuCompte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le compte {0} a déjà été sélectionné..
        '''</summary>
        Friend Shared ReadOnly Property PLC_CompteDejaSelect() As String
            Get
                Return ResourceManager.GetString("PLC_CompteDejaSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le compte {0} existe déjà pour cet exercice..
        '''</summary>
        Friend Shared ReadOnly Property PLC_CompteExiste() As String
            Get
                Return ResourceManager.GetString("PLC_CompteExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le compte {0}-{1} est déjà dans le plan comptable de cet exercice..
        '''</summary>
        Friend Shared ReadOnly Property PLC_CoupleExiste() As String
            Get
                Return ResourceManager.GetString("PLC_CoupleExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Création des comptes....
        '''</summary>
        Friend Shared ReadOnly Property PLC_CreationDesComptes() As String
            Get
                Return ResourceManager.GetString("PLC_CreationDesComptes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter une activité....
        '''</summary>
        Friend Shared ReadOnly Property PLC_CreerActi() As String
            Get
                Return ResourceManager.GetString("PLC_CreerActi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enlever les activités sélectionnées.
        '''</summary>
        Friend Shared ReadOnly Property PLC_EnleverActi() As String
            Get
                Return ResourceManager.GetString("PLC_EnleverActi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le compte {0} ne correspond à aucune racine comptable..
        '''</summary>
        Friend Shared ReadOnly Property PLC_PasDansPlanType() As String
            Get
                Return ResourceManager.GetString("PLC_PasDansPlanType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélectionnez ou saisissez les activités à affecter aux comptes.
        '''</summary>
        Friend Shared ReadOnly Property PLC_SelectActi() As String
            Get
                Return ResourceManager.GetString("PLC_SelectActi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection des activités.
        '''</summary>
        Friend Shared ReadOnly Property PLC_SelectActi2() As String
            Get
                Return ResourceManager.GetString("PLC_SelectActi2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible de supprimer le couple {1}/{2} car il est utilisé..
        '''</summary>
        Friend Shared ReadOnly Property PLC_SuppressionImpossible() As String
            Get
                Return ResourceManager.GetString("PLC_SuppressionImpossible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer ce compte ?.
        '''</summary>
        Friend Shared ReadOnly Property PLC_VerifSupprCompte() As String
            Get
                Return ResourceManager.GetString("PLC_VerifSupprCompte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Récupération des informations....
        '''</summary>
        Friend Shared ReadOnly Property RecupInfos() As String
            Get
                Return ResourceManager.GetString("RecupInfos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Restauration.
        '''</summary>
        Friend Shared ReadOnly Property Restauration() As String
            Get
                Return ResourceManager.GetString("Restauration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sauvegarde est endommagée..
        '''</summary>
        Friend Shared ReadOnly Property Restauration_SauvegardeEndommagee() As String
            Get
                Return ResourceManager.GetString("Restauration_SauvegardeEndommagee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cet exercice est déjà présent sur votre ordinateur. Souhaitez vous l&apos;écraser ?.
        '''</summary>
        Friend Shared ReadOnly Property Restore_AskEcraserDossier() As String
            Get
                Return ResourceManager.GetString("Restore_AskEcraserDossier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucune sauvegarde disponible pour le fichier &apos;{0}{1}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property Restore_AucuneSauvegardeDisponible() As String
            Get
                Return ResourceManager.GetString("Restore_AucuneSauvegardeDisponible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Restauration annulée.
        '''</summary>
        Friend Shared ReadOnly Property Restore_Cancel() As String
            Get
                Return ResourceManager.GetString("Restore_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lecture de la sauvegarde....
        '''</summary>
        Friend Shared ReadOnly Property Restore_LectureDeLaSauvegarde() As String
            Get
                Return ResourceManager.GetString("Restore_LectureDeLaSauvegarde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Probleme de lecture du fichier : .
        '''</summary>
        Friend Shared ReadOnly Property Restore_ProblemeDeLectureDuFichier() As String
            Get
                Return ResourceManager.GetString("Restore_ProblemeDeLectureDuFichier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La restauration n&apos;a pas pu être réalisée à cause des problèmes suivants :.
        '''</summary>
        Friend Shared ReadOnly Property Restore_RecapProblemes() As String
            Get
                Return ResourceManager.GetString("Restore_RecapProblemes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le répertoire de sauvegarde est introuvable..
        '''</summary>
        Friend Shared ReadOnly Property Restore_RepertoireEstIntrouvable() As String
            Get
                Return ResourceManager.GetString("Restore_RepertoireEstIntrouvable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sauvegarde de &apos;{0}{1}&apos; du {2:dd/MM/yy HH:mm} a été restaurée.
        '''</summary>
        Friend Shared ReadOnly Property Restore_Restauree() As String
            Get
                Return ResourceManager.GetString("Restore_Restauree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Restauration effectuée avec succès.
        '''</summary>
        Friend Shared ReadOnly Property Restore_Succes() As String
            Get
                Return ResourceManager.GetString("Restore_Succes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous devez avoir des lignes pour effectuer la TVA.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_AppelTVASansLignes() As String
            Get
                Return ResourceManager.GetString("Saisie_AppelTVASansLignes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Souhaitez vous réinitialiser toutes les lignes de contrepartie ?.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_AskResetContrepartie() As String
            Get
                Return ResourceManager.GetString("Saisie_AskResetContrepartie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention : toutes les lignes ayant un compte de contre partie seront supprimées et réécrites.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_AskResetContrePartie2() As String
            Get
                Return ResourceManager.GetString("Saisie_AskResetContrePartie2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Souhaitez-vous réinitialiser toutes les lignes de TVA ?.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_AskResetTVA() As String
            Get
                Return ResourceManager.GetString("Saisie_AskResetTVA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention : toutes les lignes ayant un compte TVA seront supprimées et ré-écrites.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_AskResetTVA2() As String
            Get
                Return ResourceManager.GetString("Saisie_AskResetTVA2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention, la TVA n&apos;a pas pu être calculée pour certaines lignes..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_AttentionPasPuCalcTVA() As String
            Get
                Return ResourceManager.GetString("Saisie_AttentionPasPuCalcTVA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucune pièce à enregistrer.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_AucunePiece() As String
            Get
                Return ResourceManager.GetString("Saisie_AucunePiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Votre comptabilité est clôturée, vous ne pouvez pas ajouter de pièce..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_BlocageCloture() As String
            Get
                Return ResourceManager.GetString("Saisie_BlocageCloture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible de supprimer une pièce unique..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_BloquageSupprDernierePiece() As String
            Get
                Return ResourceManager.GetString("Saisie_BloquageSupprDernierePiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Saisie des montants en TTC.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_CheckSaisieDesMontantsEnTTC() As String
            Get
                Return ResourceManager.GetString("Saisie_CheckSaisieDesMontantsEnTTC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez changer le numéro de la pièce et/ou la date, car celle ci existe déjà..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_CollisionPiece() As String
            Get
                Return ResourceManager.GetString("Saisie_CollisionPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible d&apos;intégrer la pièce {0}, elle existe déjà en base.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_CollisionPieces() As String
            Get
                Return ResourceManager.GetString("Saisie_CollisionPieces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Compte introuvable dans le plan type.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_CompteIntrouvableDansLePlanType() As String
            Get
                Return ResourceManager.GetString("Saisie_CompteIntrouvableDansLePlanType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Journal en cours : .
        '''</summary>
        Friend Shared ReadOnly Property Saisie_JournalEnCours() As String
            Get
                Return ResourceManager.GetString("Saisie_JournalEnCours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez pas enregistrer la pièce car elle comporte des lignes en erreur..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_LignesEnErreur() As String
            Get
                Return ResourceManager.GetString("Saisie_LignesEnErreur", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez pas enregistrer la pièce {0}. Elle comporte des lignes en erreur..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_LignesEnErreurDansPiece() As String
            Get
                Return ResourceManager.GetString("Saisie_LignesEnErreurDansPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous avez des lignes sans montant au débit ni au crédit.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_LignesSansMontant() As String
            Get
                Return ResourceManager.GetString("Saisie_LignesSansMontant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous avez des lignes sans montant au débit ou au crédit dans la pièce {0}..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_LignesSansMontantDansPiece() As String
            Get
                Return ResourceManager.GetString("Saisie_LignesSansMontantDansPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ce numéro de pièce existe déjà.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_NumeroExistant() As String
            Get
                Return ResourceManager.GetString("Saisie_NumeroExistant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La pièce est vide.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_PbPieceVide() As String
            Get
                Return ResourceManager.GetString("Saisie_PbPieceVide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez pas modifier la pièce {0}. Elle a déjà été exportée..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_PieceDejaExporteDansPiece() As String
            Get
                Return ResourceManager.GetString("Saisie_PieceDejaExporteDansPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez pas modifier cette pièce. Elle a déjà été exportée..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_PieceDejaExportee() As String
            Get
                Return ResourceManager.GetString("Saisie_PieceDejaExportee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cette pièce n&apos;existe pas.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_PieceInexistante() As String
            Get
                Return ResourceManager.GetString("Saisie_PieceInexistante", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Piece supprimée.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_PieceSupprimee() As String
            Get
                Return ResourceManager.GetString("Saisie_PieceSupprimee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous avez des pièces ayant une mauvaise date ou numéro de pièce.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_ProblemeDateNum() As String
            Get
                Return ResourceManager.GetString("Saisie_ProblemeDateNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez équilibrer vos écritures.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_ProblemeEquilibre() As String
            Get
                Return ResourceManager.GetString("Saisie_ProblemeEquilibre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez équilibrer vos écritures sur la pièce {0}..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_ProblemeEquilibrePourPiece() As String
            Get
                Return ResourceManager.GetString("Saisie_ProblemeEquilibrePourPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucune pièce n&apos;est sélectionnée.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_ProblemeSelection() As String
            Get
                Return ResourceManager.GetString("Saisie_ProblemeSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez sélectionner un journal.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_SelectionJournal() As String
            Get
                Return ResourceManager.GetString("Saisie_SelectionJournal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à  Solde de base : {0:C2}.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_SoldeDeBase() As String
            Get
                Return ResourceManager.GetString("Saisie_SoldeDeBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez pas solder la pièce avec ce compte..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_SoldeImpossibleSurCpte() As String
            Get
                Return ResourceManager.GetString("Saisie_SoldeImpossibleSurCpte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Clôture de pièce.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_SolderPiece() As String
            Get
                Return ResourceManager.GetString("Saisie_SolderPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Consultation de la pièce.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_TextConsultation() As String
            Get
                Return ResourceManager.GetString("Saisie_TextConsultation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Consultation des pièces sur bordereau.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_TextConsultationBordereau() As String
            Get
                Return ResourceManager.GetString("Saisie_TextConsultationBordereau", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La quantité saisie n&apos;est pas conforme. Veuillez vérifier votre saisie.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_VerifConformiteQte() As String
            Get
                Return ResourceManager.GetString("Saisie_VerifConformiteQte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer toutes les lignes de cette pièce ?.
        '''</summary>
        Friend Shared ReadOnly Property Saisie_VerifResetPiece() As String
            Get
                Return ResourceManager.GetString("Saisie_VerifResetPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez vérifier le solde de votre pièce..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_VerifSolde() As String
            Get
                Return ResourceManager.GetString("Saisie_VerifSolde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir des lignes..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_VeuillezSaisirDesLignes() As String
            Get
                Return ResourceManager.GetString("Saisie_VeuillezSaisirDesLignes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir la TVA..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_VeuillezSaisirLaTVA() As String
            Get
                Return ResourceManager.GetString("Saisie_VeuillezSaisirLaTVA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir tous les montants de TVA..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_VeuillezSaisirMontantTVA() As String
            Get
                Return ResourceManager.GetString("Saisie_VeuillezSaisirMontantTVA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir une quantité..
        '''</summary>
        Friend Shared ReadOnly Property Saisie_VeuillezSaisirUneQte() As String
            Get
                Return ResourceManager.GetString("Saisie_VeuillezSaisirUneQte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Saisie incomplète.
        '''</summary>
        Friend Shared ReadOnly Property SaisieIncomplete() As String
            Get
                Return ResourceManager.GetString("SaisieIncomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Calcul de TVA.
        '''</summary>
        Friend Shared ReadOnly Property Sasie_CalculDeTVA() As String
            Get
                Return ResourceManager.GetString("Sasie_CalculDeTVA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sauvegarde.
        '''</summary>
        Friend Shared ReadOnly Property Sauvegarde() As String
            Get
                Return ResourceManager.GetString("Sauvegarde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sauvegarde achevée....
        '''</summary>
        Friend Shared ReadOnly Property Sauvegarde_Achevee() As String
            Get
                Return ResourceManager.GetString("Sauvegarde_Achevee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Compression des données....
        '''</summary>
        Friend Shared ReadOnly Property Sauvegarde_CompressionDesDonnees() As String
            Get
                Return ResourceManager.GetString("Sauvegarde_CompressionDesDonnees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La sauvegarde n&apos;a pas pu être réalisée à cause des problèmes suivants :.
        '''</summary>
        Friend Shared ReadOnly Property Sauvegarde_RecapProblemes() As String
            Get
                Return ResourceManager.GetString("Sauvegarde_RecapProblemes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sauvegarde réalisée avec succès.
        '''</summary>
        Friend Shared ReadOnly Property Sauvegarde_Succes() As String
            Get
                Return ResourceManager.GetString("Sauvegarde_Succes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection de date.
        '''</summary>
        Friend Shared ReadOnly Property SelectionDate() As String
            Get
                Return ResourceManager.GetString("SelectionDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez choisir une date inférieure à la date de fin.
        '''</summary>
        Friend Shared ReadOnly Property SelectionDate_DateInferieureADateFin() As String
            Get
                Return ResourceManager.GetString("SelectionDate_DateInferieureADateFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Souhaitez vous continuer ?.
        '''</summary>
        Friend Shared ReadOnly Property SouhaitezVousContinuer() As String
            Get
                Return ResourceManager.GetString("SouhaitezVousContinuer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Suppression.
        '''</summary>
        Friend Shared ReadOnly Property Suppression() As String
            Get
                Return ResourceManager.GetString("Suppression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Suppression annulée.
        '''</summary>
        Friend Shared ReadOnly Property SuppressionAnnulee() As String
            Get
                Return ResourceManager.GetString("SuppressionAnnulee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Suppression d&apos;exercice.
        '''</summary>
        Friend Shared ReadOnly Property SuppressionDeDossier() As String
            Get
                Return ResourceManager.GetString("SuppressionDeDossier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Suppression d&apos;une pièce.
        '''</summary>
        Friend Shared ReadOnly Property SuppressionDePiece() As String
            Get
                Return ResourceManager.GetString("SuppressionDePiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Suppression d&apos;exploitation.
        '''</summary>
        Friend Shared ReadOnly Property SuppressionDExploitation() As String
            Get
                Return ResourceManager.GetString("SuppressionDExploitation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Etes vous sur de vouloir supprimer le modèle {0}?.
        '''</summary>
        Friend Shared ReadOnly Property SuppressionModele() As String
            Get
                Return ResourceManager.GetString("SuppressionModele", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer la pièce : {0} du {1:dd/MM/yy} ?.
        '''</summary>
        Friend Shared ReadOnly Property SuppressionPiece() As String
            Get
                Return ResourceManager.GetString("SuppressionPiece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à  - Ultra VNC : Téléintervention en cours.
        '''</summary>
        Friend Shared ReadOnly Property TeleinterventionEnCours() As String
            Get
                Return ResourceManager.GetString("TeleinterventionEnCours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Transfert de pièce.
        '''</summary>
        Friend Shared ReadOnly Property TransfertDossier() As String
            Get
                Return ResourceManager.GetString("TransfertDossier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention : des pièces vont être transférées vers l&apos;exercice {0} depuis l&apos;exercice {1}..
        '''</summary>
        Friend Shared ReadOnly Property TransfertDossier_MsgAttention1() As String
            Get
                Return ResourceManager.GetString("TransfertDossier_MsgAttention1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La nouvelle date de début d&apos;exercice du dossier {1} va devenir {2:dd/MM/yyyy}..
        '''</summary>
        Friend Shared ReadOnly Property TransfertDossier_MsgAttention2DEB() As String
            Get
                Return ResourceManager.GetString("TransfertDossier_MsgAttention2DEB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La nouvelle date de fin d&apos;exercice du dossier {1} va devenir {2:dd/MM/yyyy}..
        '''</summary>
        Friend Shared ReadOnly Property TransfertDossier_MsgAttention2FIN() As String
            Get
                Return ResourceManager.GetString("TransfertDossier_MsgAttention2FIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Problème lors des transferts de pièces vers un autre exercice.
        '''</summary>
        Friend Shared ReadOnly Property TransfertDossier_Pb() As String
            Get
                Return ResourceManager.GetString("TransfertDossier_Pb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vous ne pouvez pas transférer les pièces car il n&apos;existe pas d&apos;exercice et vous ne pouvez pas en créer..
        '''</summary>
        Friend Shared ReadOnly Property TransfertDossier_PbDossierInexistant() As String
            Get
                Return ResourceManager.GetString("TransfertDossier_PbDossierInexistant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La téléintervention peut commencer.
        '''</summary>
        Friend Shared ReadOnly Property UltraVNC_Debut() As String
            Get
                Return ResourceManager.GetString("UltraVNC_Debut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La téléintervention est terminée.
        '''</summary>
        Friend Shared ReadOnly Property UltraVNC_Fin() As String
            Get
                Return ResourceManager.GetString("UltraVNC_Fin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Etes vous sur de vouloir supprimer cet enregistrement?.
        '''</summary>
        Friend Shared ReadOnly Property VerifSuppression() As String
            Get
                Return ResourceManager.GetString("VerifSuppression", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
